### ISSUE TITLE
add a customers booking

### ISSUE THREAD

**Issue by s3383022** [s3383022/SoftEng_2017_ABS#16]
@RedBeardCory  The addBooking method in the customer booking section isn't adding the booking read from the file.

**Comment by s3383022** [comment]
`if (this.bookings == null) {
			this.bookings.add(booking);
}`

Seemed to fix it.

**Comment by RedBeardCory** [comment]
sorry, didn't think of that one. It's added, if you could merge that would be awesome :)

**Comment by s3383022** [comment]
resolved with #18
